version: 1
formatters:
  default:
    format: "%(levelprefix)s %(message)s"
handlers:
  default:
    class: logging.StreamHandler
    stream: ext://sys.stderr
    formatter: default
root:
  handlers: [default]
  level: INFO
