version: 1
disable_existing_loggers: False
formatters:
  default:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  access:
    format: "%(asctime)s - %(name)s - %(levelname)s - %(client_addr)s - \"%(request_line)s\" %(status_code)s"
handlers:
  default:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: default
  access:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: access
loggers:
  uvicorn:
    level: INFO
    handlers: [default]
    propagate: no
  uvicorn.error:
    level: INFO
    handlers: [default]
    propagate: no
  uvicorn.access:
    level: INFO
    handlers: [access]
    propagate: no
  fastapi:
    level: INFO
    handlers: [default]
    propagate: no
root:
  handlers: [default]
  level: INFO
